# Generated by Django 4.0.6 on 2022-07-20 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_product_remove_orderitem_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client',
            new_name='owner',
        ),
    ]
