# Generated by Django 4.0.6 on 2022-07-19 19:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_journalentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
