# Generated by Django 4.0.6 on 2022-07-19 19:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_populate_barcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
