# Generated by Django 4.0.6 on 2022-07-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_uuid_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
        ),
    ]
