# Generated by Django 4.0.6 on 2022-07-20 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_journalentry_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='owner',
        ),
    ]
